### ISSUE TITLE
Why change parameters in ARX mean model effect GARCH forecast

### ISSUE THREAD

**Issue by DanielZJInvest** [bashtage/arch#269]
Firstly I defined a AR(1)-GARCH(1,1) model. Then fit the model with generated sample and perform 1-step a head forecast. However, if I change the parameters of AR model, the forecast of residual-variance also changes. Should GARCH variance forecast irrelevant with AR model?
please  see the example

```

import pandas as pd
import numpy as np
from arch import arch_model

sample = pd.Series(np.random.rand(1000,))


a = arch_model(sample,mean='ARX', lags=1, vol='GARCH', p=1, o=0, q=1,power=2.0, dist='normal', hold_back=None).fit()
f = a.forecast()
print(f.residual_variance.iloc[-1])

new_param = a.params.copy()
new_param.iloc[0:2] = [0,0]

print(a.forecast(new_param).residual_variance.iloc[-1])
```

Why would residual_variance change?

**Comment by bashtage** [comment]
It treats the parameters as-if these are the estimated model parameters, and so changing the mean parameters changes the history of the innovations, which then change the residual variance forecast.  

This is also kind of essential in some applications since forecasts can be produced from a model without estimation -- hence the only parameters available are the 

This probably isn't the best choice.  Fixing this is non-trivial and so will take a while. Will probably need a new keyword argument, e.g., `forecast_params=None` which are only used if provided, so that these can be separately specified.

**Comment by DanielZJInvest** [comment]
Thank you for the quick response. So the residues/innovations are changed by the mean model.  I tried to dig into the code with variance calculation and recursion related part, but didn't find the place where innovation was changed. Anyway, good to know the reason. It would cost time to modify the code but cost little to write the forecast myself. Thanks again

**Comment by bashtage** [comment]
Line 631 of mean.py is where the parameters passed to forecast are used to compute all of the residuals.
