### ISSUE TITLE
ENH: Add warning when data set size is large and lags is not directly set

### ISSUE THREAD

**Issue by cTatu** [bashtage/arch#606]
Hi,

I was wondering if there was a way to make the unit root tests faster.
I have multiple dataset consisting of hundreds of millions of samples each. 
The computation takes hours and it's only using 1 core from all 160 cores that I have available.
I will need to run this multiples times in a iterative process so waiting so much just for 1 test is pretty unfeasible.
Could be there an easy way to enable parallelization using for example ProcessPoolExecutors? or even GPU through Cupy?

Thank you

**Comment by bashtage** [comment]
A couple of things.

1. DFGLS is a waste in large dataset.  The reason DFGLS was created was low power in small samples.  With 1000+ point datasets,  there is no reason to not just use ADF
2. In both ADF and DFGLS  it is essential to minit max lags to something small when datasets are large.  The default uses a value that grows with sample size,  so that in very large datasets the effective maxlags is extremely large,  which makes estimation show.

**Comment by bashtage** [comment]
I just did a quick check and the big problem with large datasets is the autolag.  It does a search across 0, 1, 2, ... max_lags lags in the model which is slow. You can get large speedups by setting a specific number of lags, even if it is fairly high. I quick profile with 10,000,000 observations

![image](https://user-images.githubusercontent.com/5585221/185893597-7f6a305a-5d55-42b7-b7b3-65de18ba9e8a.png)

If you set `lags` it is much faster.  

It is also multi-threaded when fitting the actual model since it relies on BLAS (you should use a good BLAS, either MKL or OpenBLAS - this will be automatic in most cases, unless you compile your own NumPy).

**Comment by bashtage** [comment]
Here is a comparrison with 10,000,000 obs

```
In [5]: %timeit DFGLS(y, lags=10).stat
7.77 s ± 119 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit DFGLS(y).stat
1min 54s ± 3.94 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

The most observations you have, the larger the difference will get.

**Comment by cTatu** [comment]
Setting the `lags` solved the problem. The time was reduced more than x20!
Thank you very much ✌️

**Comment by bashtage** [comment]
You are welcome.  I am going to reopen this since it would be good to have some sort of warning in this case.  Pretty sure this has come up before either here or on SO.

Could also default faster way in these cases, e.g., simple-to-general search with a stopping rule.
