### ISSUE TITLE
normalization constant in EGARCH doesn't handle StudentsT correctly

### ISSUE THREAD

**Issue by fermionportal** [bashtage/arch#64]
According to
http://uk.mathworks.com/help/econ/egarch-model.html
or
https://www.quantnet.com/threads/expectation-of-folded-students-t.15825/

the norm_const in EGARCH simulate() function, in case of studentsT distribution, should be:
np.sqrt((nu-2)/3.1415) * scipy.special.gamma((nu-1)/2) / scipy.special.gamma(nu/2)

**Comment by bashtage** [comment]
This recentering has no effect on the model since the intercept can freely adjust.  The fit will be the same for any centering.  It is merely a presentation device.




On Thu, May 7, 2015 at 3:35 AM -0700, "fermionportal" <notifications@github.com<mailto:notifications@github.com>> wrote:


According to
http://uk.mathworks.com/help/econ/egarch-model.html
or
https://www.quantnet.com/threads/expectation-of-folded-students-t.15825/

the norm_const in EGARCH simulate() function, in case of studentsT distribution, should be:
np.sqrt((nu-2)/3.1415) * scipy.special.gamma((nu-1)/2) / scipy.special.gamma(nu/2)

**Comment by fermionportal** [comment]
From your post, I understand that the fitted omega value is already adjusted for nu and alpha parameters ? This is not obvious from the fit routine. 
Otherwise the simulations will be off by the "centering".

**Comment by bashtage** [comment]
If you use values estimated from EGARCH to simulate then nothign will be off.  If the parameters were estimated using a different centering, a little trivial math is needed to change the value of omega to reflect this.  It is completely correct to write the EGARCH model with no centering - all that matters is that the same centering is used for estimation/simulation/forecasting/etc.
